### ISSUE TITLE
Documentation update: Google Cloud Storage and service accounts

### ISSUE THREAD

**Issue by cireficc** [fog/fog-google#385]
I have looked *everywhere* through Fog documentation, CarrierWave, etc. and no documentation seems to show the correct process for using CarrierWave/Fog with Cloud Storage using a service account (JSON credentials).

[This issue](https://github.com/fog/fog-google/issues/60) talks about issues with using a service account, but gives no solution. It's also 3 years old.

The [Fog website](http://fog.io/storage) shows how to use the old mechanism for authentication, Interoperable Access. The Fog examples in this repository also use the old method. I'd like to use the current and future-proof mechanism of service accounts so that I don't have to migrate it in the future.

After 2 days of on-and-off tinkering with various configurations and looking through the [codebase](https://github.com/fog/fog-google/blob/6a1e8d2622a771bc678e5ecb9b84b15b4e955cca/lib/fog/google/shared.rb#L20), I finally found the one that worked. Here is the minimal example code:

**config/initializers/carrierwave.rb**
```ruby
CarrierWave.configure do |config|
    config.fog_provider = 'fog/google'
    config.fog_credentials = {
        provider: 'Google',
        google_project: Rails.application.secrets.google_cloud_storage_project_name,
        google_json_key_string: Rails.application.secrets.google_cloud_storage_credential_content
        # can optionally use google_json_key_location if using an actual file;
        # however, I am using **Heroku** where you can't store physical files unless you
        # check them into the repo (and you don't want to do that with service account credentials!)
    }
    config.fog_directory = Rails.application.secrets.google_cloud_storage_bucket_name
end
```

**config/secrets.yml**
```yaml
development:
    google_cloud_storage_project_name: your-project-name
    google_cloud_storage_credential_content: '{
        "type": "service_account",
        "project_id": "your-project-name",
        "private_key_id": "REDACTED",
        "private_key": "-----BEGIN PRIVATE KEY-----REDACTED-----END PRIVATE KEY-----\n",
        "client_email": "REDACTED@your-project-name.iam.gserviceaccount.com",
        "client_id": "REDACTED",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/REDACTED%40your-project-name.iam.gserviceaccount.com"
    }'
    google_cloud_storage_bucket_name: your-bucket-name
```

It's really not complicated, but it took me too long to figure out how to get this to work with JSON credentials where I couldn't store the file on the filesystem. Heroku allows multi-line environment variables, so that's what I'll be using.

**Can the [fog website documentation](http://fog.io/storage) be updated to reflect the new JSON service account key authentication mechanism?**
